config/routes.rb
Rails.application.routes.draw do

  resources :articles do
  	resources :comments
	end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :nama, presence: true, length: {minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	  http_basic_authenticate_with name: "tonsi", password: "rahasia", except: [:index, :show]
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

		def edit
		@article = Article.find(params[:id])
	end
	
	def create
		@article = Article.new(article_params)

		if @article.save
		redirect_to @article
	else
		render 'new'
	end
end
		def update
			@article = Article.find(params[:id])
			if @article.update(article_params)
			redirect_to @article
		else
			render 'Edit'
		end
end

		def destroy
			@article = Article.find(params[:id])
			@article.destroy

			redirect_to articles_path
		end

	private
		def article_params
			params.require(:article).permit(:nama, :email, :telepon, :alamat)
			
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  http_basic_authenticate_with name: "tonsi", password: "rahasia", only: :destroy
 
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Nama %><br>
    <%= form.text_field :nama %>
  </p>
 
  <p>
    <%= form.label :Email%><br>
    <%= form.text_field :email %>
  </p>
 

  <p>
    <%= form.label :Telepon %><br>
    <%= form.text_field :telepon %>
  </p>
 
  <p>
    <%= form.label :Alamat %><br>
    <%= form.text_field :alamat %>
  </p>

  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Artikel</h1>

<%= render 'form' %> 
<%= link_to 'Kembali', articles_path %>

app/views/articles/index.html.erb
<h1 class="tonsi">
Daftar Hadir</h1>
  <a href="/articles/new" class="btn btn-primary btn-lg active role="button" aria-pressed="true">Artikel Baru</a><br><br>
 
<div class="row">
  <div class="col-md-6 col-sm-6">
      <table class="table table-bordered table-responsive">
        <thead class="thead-dark">
      <tr>
      <th scope="colspan">No</th>
      <th scope="colspan">Nama</th>
      <th scope="colspan">Email</th>
      <th scope="colspan">Telepon</th>
      <th scope="colspan">Alamat</th>
      <th colspan="2"><center>Aksi</center></th>
    
  </tr>
</thead>
 
    <% i = 0 %>
    <ul id="articles">
    <% @articles.each do |article| %>
    <% i+=1 %> 
 </ul>
    <tr>
      <td><%= "#{i}" %></td>
      <td><%= article.nama %></td>
      <td><%= article.email %></td>
      <td><%= article.telepon %></td>
      <td><%= article.alamat %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <!-- <td><%= link_to 'Edit', edit_article_path(article) %></td> -->
      <td><%= link_to 'Destroy', article_path(article), method: :delete, 
        data: { confirm: 'Are You sure'} %></td>
    </tr>
  <% end %>

</table>
</div>
</div>

<div>
  <div class="col-md-6" col-sm-6>
  

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="home/arjuna/project/app/assets/images/hhh.jpeg" alt="Card image cap">
     
</div>
</div>
      <%= link_to 'Kembali', articles_path  %>

app/views/articles/new.html.erb
<h1>Artikel Baru</h1>

<%= render 'form' %>
<%= link_to 'Kembali', articles_path %>

app/views/articles/show.html.erb
  <p>
	<strong>Nama</strong>
	<%= @article.nama %>
</p>

<p>
	<strong>Email</strong>
	<%= @article.email %>
</p>

<p>
	<strong>Telepon</strong>
	<%= @article.telepon %>
</p>

<p>
	<strong>Alamat</strong>
	<%= @article.alamat %>
</p>
</table>

<h2>Comments</h2>
  <% @article.comments.each do |comment| %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>
  
    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>

<% end %>
 
<h2>Add a comment:</h2>
  <%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
      <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
      </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

<p>
      <%= form.submit %>
</p>

<% end %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Kembali', articles_path %>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter</strong>
	<%= comment.commenter %>
</p>

<p>
	<strong>Comments</strong>
	<%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Selamat Datang</h1>